name: common_core
description: "A new Flutter Model."

version: 1.0.0+1
#publish_to: none  # 表示这是本地包

environment:
  sdk: ^3.7.0-209.1.beta


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2                  #日期格式化
  #网络
  dio:                        #https://pub-web.flutter-io.cn/packages/dio
  talker_dio_logger:          #https://pub-web.flutter-io.cn/packages/talker_dio_logger
  talker_flutter: ^5.0.0
  chucker_flutter:            #https://pub-web.flutter-io.cn/packages/chucker_flutter
  logger:                     #https://pub-web.flutter-io.cn/packages/logger
  get:                        #https://pub-web.flutter-io.cn/packages/get
  #必备
  flutter_native_splash:      #https://pub-web.flutter-io.cn/packages/flutter_native_splash
  flutter_launcher_icons:     #https://pub-web.flutter-io.cn/packages/flutter_launcher_icons
  cached_network_image:       #https://pub-web.flutter-io.cn/packages/cached_network_image
  flutter_smart_dialog:       #https://juejin.cn/post/7026150456673959943  #使用例子 https://xdd666t.github.io/flutter_use/web/index.html#/smartDialog?dialogType=CustomDialogLocation
  package_info_plus:          #https://pub-web.flutter-io.cn/packages/package_info_plus
  shared_preferences:         #https://pub-web.flutter-io.cn/packages/shared_preferences/install
  webview_flutter:            #https://pub.dev/packages/webview_flutter
  permission_handler:         #https://pub-web.flutter-io.cn/packages/permission_handler/example
  device_info_plus:           #https://pub-web.flutter-io.cn/packages/device_info_plus/example
  flutter_local_notifications: #https://pub-web.flutter-io.cn/packages/flutter_local_notifications
#  connectivity_plus:           #https://pub-web.flutter-io.cn/packages/connectivity_plus
  #组件
  extended_image:             #https://pub-web.flutter-io.cn/packages/extended_image
  dd_check_plugin: ^5.1.0     #https://pub-web.flutter-io.cn/packages/dd_check_plugin
  #-------------------下拉刷新加载更多------------
  any_refreshable_widget:     #https://pub-web.flutter-io.cn/packages/any_refreshable_widget
  custom_refresh_indicator:   #https://pub.dev/packages/custom_refresh_indicator/install
  paging_view:                #https://pub.dev/packages/paging_view
  easy_refresh:               #https://pub.dev/packages/easy_refresh/example
  smart_scroll:               #https://pub.dev/packages/smart_scroll
  #pull_to_refresh: ^2.0.0    #https://github.com/peng8350/flutter_pulltorefresh
  #---------------------------------------------
  path_provider:              #https://pub-web.flutter-io.cn/packages/path_provider
  image_picker:               #https://pub-web.flutter-io.cn/packages/image_picker
  url_launcher:               #https://pub-web.flutter-io.cn/packages/url_launcher/install
  flutter_constraintlayout:   #https://github.com/hackware1993/Flutter_ConstraintLayout/blob/master/README_CN.md
  extended_sliver:            #https://pub-web.flutter-io.cn/packages/extended_sliver
  photo_view:                 #https://pub-web.flutter-io.cn/packages/photo_view
  scrollview_observer:        #https://pub.dev/packages/scrollview_observer
  carousel_slider:            #https://pub-web.flutter-io.cn/packages/carousel_slider
  #animate
  animate_do:                 #https://pub-web.flutter-io.cn/packages/animate_do
  animations:                 #https://pub-web.flutter-io.cn/packages/animations
  flutter_animate:            #https://pub-web.flutter-io.cn/packages/flutter_animate
  #工具
  open_filex:                  #https://pub-web.flutter-io.cn/packages/open_filex

  #  fl_paging: ^2.3.0         #https://pub.dev/packages/fl_paging
  #  super_paging: ^0.2.0      #https://pub.dev/packages/super_paging
  #  video_player: ^2.9.5      #https://pub.dev/packages/video_player

  #https://github.com/OctMon/flutter_easy
  #工具
  dart_helper_utils:           #https://pub.dev/packages/dart_helper_utils
  nb_utils:                    #https://pub.dev/packages/nb_utils
  basic_utils:                 #https://pub.dev/packages/basic_utils
  screwdriver:                 #https://pub.dev/packages/screwdriver   //作用域
  flutter_helper_utils:        #https://pub.dev/packages/flutter_helper_utils
  flutter_helper_kit:          #https://pub.dev/packages/flutter_helper_kit
  sprintf:                     #https://pub-web.flutter-io.cn/packages/sprintf
  flutter_websocket_manager: ^1.0.4
  #支付
  in_app_purchase: ^3.2.3      #https://pub-web.flutter-io.cn/packages/in_app_purchase
  in_app_purchase_storekit: ^0.4.6+2

  firebase_auth:
  firebase_core:
  firebase_analytics:
  firebase_messaging:
  firebase_crashlytics:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/
  #  fonts:
  #    - family: DINPRO
  #      fonts:
  #        - asset: assets/fonts/dinpro.ttf
  #        - asset: assets/fonts/dinpro_bold.ttf
  #        - asset: assets/fonts/dinpro_medium.ttf



  module:
    androidX: true
    androidPackage: com.xueh.common_core
    iosBundleIdentifier: com.xueh.commonCore
